### ISSUE TITLE
how to make the output of vl_simplenn has the same Matrix dimensions 

### ISSUE THREAD

**Issue by pliu007** [huangzehao/caffe-vdsr#12]
function impred = runVDSR(net, imlow, gpu)
net2.layers = net.layers(1:end-1);
res2 = vl_simplenn(net2, imlow, []); 
impred = res2(end).x;
impred = imlow+impred;
if gpu, impred = gather(impred); end

When I run the code mentioned above, I got the error shown as the blow:

run testVDSR.m
255 255
295 295

Error using +
Matrix dimensions must agree.

Error in runVDSR (line 8)
impred = imlow+impred;

Error in VDSR (line 47)
impred = runVDSR(net, imlowy, gpu);

Error in testVDSR (line 13)
VDSR(data, SF, 'VDSR.mat', outRoute);

Error in run (line 63)
evalin('caller', [script ';']);

Anyone can help me out ? the imlow is the input image 255255. but the output is 295295. is there anything wrong with my code??

Thank you !

**Comment by huangzehao** [comment]
Obviously the problem occurred in your trained network. Check the dimensions of output of each layer in res2 and you will know the problem.

**Comment by pliu007** [comment]
I just use the VDSR official code and trained model.  I find the VDSR.mat can not be opened by Matlab, error info shown as below,  but the VDSR_Official.mat in your code folder can be opened.   

Caused by:
    The CUDA driver was found, but the function 'cuDriverGetVersion' returned an error. The error returned was:
    CUDA_ERROR_NOT_INITIALIZED

do you why?

**Comment by huangzehao** [comment]
The parameters in VDSR.mat are stored in gpuArray format. If you don't have a gpu or there are some problem in the gpu usage, this problem will arise.

发自我的 iPhone

在 2016年9月25日，12:29，Peng Liu <notifications@github.com<mailto:notifications@github.com>> 写道：

I just use the VDSR official code and trained model. I find the VDSR.mat can not be opened by Matlab, error info shown as below, but the VDSR_Official.mat in your code folder can be opened.

Caused by:
The CUDA driver was found, but the function 'cuDriverGetVersion' returned an error. The error returned was:
CUDA_ERROR_NOT_INITIALIZED

do you why?

―

**Comment by pliu007** [comment]
I got. Thank you ~!
