### ISSUE TITLE
How to decide when to low down the learning rate in an automatic way

### ISSUE THREAD

**Issue by llyydd007** [huangzehao/caffe-vdsr#2]
Hi zehao,
Excellent work! I have a question. I train the model and run with 100000 iteration without lowering down the learning rate.  Do we have an automatic way to decide when to  lower down the learning rate? Thank you!
Besides, the original paper states, 'Input patch size is now equal to the size of the receptive field and images are divided into sub-images with no overlap.' In the code, it seems the overlap existed with a stride of 14, when sub image is 41.  Is there any influences?
Thank you!

**Comment by huangzehao** [comment]
Hi llyydd01,
In order to lower down the learning rate automaticly, you should write code in caffe's solver. When the test loss isn't decrease after 5 or 10 epoches, lower down the learning rate.
I have no experience about this in caffe, you can ask this question in https://github.com/BVLC/caffe/issues. Checking the test loss during training and change the learning rate when loss doesn't decrease after several epoches. There must be some solutions in official caffe's issues. 

And actually there are not big influences in your second question. With overlap, we can get more training patches. In my opinion, more training examples is better.

**Comment by llyydd007** [comment]
Thank you!  It's so kind of you to give me quick reply~Thank you!
